name: Update VPN Subs Automatically

on:
  # Xóa sổ phần schedule (cron) để tắt chạy tự động
  workflow_dispatch: # Giữ lại cái này để mày có thể bấm nút trên GitHub hoặc trang Admin

jobs:
  update-subs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests pyyaml

      - name: Run Script
        run: python update_sub.py
